# -*- coding: utf-8 -*-
"""Read_Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IIeuM1gZykP7HCVGsWJ9r5ZXKknlHr3o
"""

import cv2
import numpy
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

img = image.load_img("k.jpg")

plt.imshow(img)

cv2.imread("k.jpg")

